import React, { useState } from 'react';
import {
  Box,
  Paper,
  Typography,
  Grid,
  Card,
  CardContent,
  Button,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
} from '@mui/material';
import {
  Description as DescriptionIcon,
  Assignment as AssignmentIcon,
  Gavel as GavelIcon,
  Warning as WarningIcon,
  CloudDownload as CloudDownloadIcon,
} from '@mui/icons-material';

const DocumentGeneration = () => {
  const [documents] = useState([
    {
      date: '2025-10-28',
      documentType: 'NDC',
      accountNumber: 'DMI0037954125',
      customerName: 'KRISHNAN THIRUVIKRAMAN',
      generatedBy: 'Super Admin',
    },
    {
      date: '2025-10-27',
      documentType: 'Settlement Letter',
      accountNumber: 'DMI0040763692',
      customerName: 'Hemalatha Jambulingam',
      generatedBy: 'Super Admin',
    },
  ]);

  const documentTypes = [
    {
      title: 'No Due Certificate (NDC)',
      description: 'Generate NDC for closed accounts',
      icon: <DescriptionIcon sx={{ fontSize: 48, color: '#9575CD' }} />,
      color: '#E1BEE7',
    },
    {
      title: 'No Objection Certificate (NOC)',
      description: 'Generate NOC for settlements',
      icon: <AssignmentIcon sx={{ fontSize: 48, color: '#FF9800' }} />,
      color: '#FFE0B2',
    },
    {
      title: 'Settlement Letter',
      description: 'Generate settlement agreement',
      icon: <GavelIcon sx={{ fontSize: 48, color: '#FFB300' }} />,
      color: '#FFF9C4',
    },
    {
      title: 'Demand Notice',
      description: 'Generate demand/legal notice',
      icon: <WarningIcon sx={{ fontSize: 48, color: '#FF9800' }} />,
      color: '#FFE0B2',
    },
  ];

  return (
    <Box sx={{ p: 2, width: '100%', height: '100%' }}>
      <Typography variant="h5" sx={{ fontWeight: 'bold', mb: 3, color: '#333' }}>
        Document Generation Center
      </Typography>

      {/* Document Type Cards */}
      <Grid container spacing={3} sx={{ mb: 4 }}>
        {documentTypes.map((doc, index) => (
          <Grid item xs={12} sm={6} md={3} key={index}>
            <Card
              sx={{
                backgroundColor: 'white',
                borderRadius: '12px',
                boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
                textAlign: 'center',
                height: '100%',
                display: 'flex',
                flexDirection: 'column',
                cursor: 'pointer',
                transition: 'transform 0.2s',
                '&:hover': {
                  transform: 'translateY(-4px)',
                  boxShadow: '0 4px 16px rgba(0,0,0,0.15)',
                },
              }}
            >
              <CardContent sx={{ flexGrow: 1, display: 'flex', flexDirection: 'column', p: 3 }}>
                <Box
                  sx={{
                    width: 80,
                    height: 80,
                    borderRadius: '50%',
                    backgroundColor: doc.color,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    mx: 'auto',
                    mb: 2,
                  }}
                >
                  {doc.icon}
                </Box>
                <Typography
                  variant="h6"
                  sx={{ fontWeight: 600, color: '#FF9A56', mb: 1 }}
                >
                  {doc.title}
                </Typography>
                <Typography variant="body2" sx={{ color: '#666' }}>
                  {doc.description}
                </Typography>
              </CardContent>
            </Card>
          </Grid>
        ))}
      </Grid>

      {/* Recently Generated Documents */}
      <Paper sx={{ borderRadius: '12px', overflow: 'hidden' }}>
        <Box sx={{ p: 2, backgroundColor: 'white' }}>
          <Typography variant="h6" sx={{ fontWeight: 600, color: '#333', mb: 2 }}>
            Recently Generated Documents
          </Typography>
        </Box>
        <TableContainer>
          <Table>
            <TableHead>
              <TableRow sx={{ backgroundColor: '#FFB84D' }}>
                <TableCell sx={{ color: 'white', fontWeight: 600 }}>Date</TableCell>
                <TableCell sx={{ color: 'white', fontWeight: 600 }}>Document Type</TableCell>
                <TableCell sx={{ color: 'white', fontWeight: 600 }}>Account Number</TableCell>
                <TableCell sx={{ color: 'white', fontWeight: 600 }}>Customer Name</TableCell>
                <TableCell sx={{ color: 'white', fontWeight: 600 }}>Generated By</TableCell>
                <TableCell sx={{ color: 'white', fontWeight: 600 }}>Actions</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {documents.map((doc, index) => (
                <TableRow
                  key={index}
                  sx={{
                    backgroundColor: index % 2 === 0 ? 'white' : '#FFF9E6',
                    '&:hover': { backgroundColor: '#FFE0B2' },
                  }}
                >
                  <TableCell>{doc.date}</TableCell>
                  <TableCell>{doc.documentType}</TableCell>
                  <TableCell sx={{ color: '#FF6B35' }}>{doc.accountNumber}</TableCell>
                  <TableCell>{doc.customerName}</TableCell>
                  <TableCell>{doc.generatedBy}</TableCell>
                  <TableCell>
                    <Button
                      variant="contained"
                      size="small"
                      startIcon={<CloudDownloadIcon />}
                      sx={{
                        backgroundColor: '#FFB84D',
                        color: 'white',
                        '&:hover': { backgroundColor: '#FF9A56' },
                        textTransform: 'none',
                        borderRadius: '8px',
                        fontWeight: 600,
                      }}
                    >
                      Download
                    </Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
      </Paper>
    </Box>
  );
};

export default DocumentGeneration;
