const mongoose = require('mongoose');
const Employee = require('../models/Employee');

// MongoDB connection string
const mongoUri = process.env.MONGODB_URI || 'mongodb://localhost:27017/crmdb';

// Dummy employee data with corrected validation
const dummyEmployees = [
  {
    empCode: 'EMP001',
    name: 'John Smith',
    branch: 'Mumbai',
    doj: new Date('2023-01-15'),
    reportingManager: 'Sarah Johnson',
    company: 'TechCorp Solutions',
    status: 'Active',
    gender: 'Male',
    dob: new Date('1990-03-15'),
    maritalStatus: 'Married',
    department: 'Software Development',
    designation: 'Senior Software Engineer',
    qualification: 'B.Tech Computer Science',
    experience: 5,
    employmentStatus: 'Permanent',
    salaryOffered: 75000,
    annual: 900000,
    contactNumber: '+91-9876543210',
    officialEmailId: 'john.smith@techcorp.com',
    personalEmailId: 'john.smith.personal@gmail.com',
    currentAddress: '123 Tech Park, Bandra West, Mumbai - 400050',
    permanentAddress: '456 Green Valley, Pune - 411001',
    panCardNo: 'ABCDE1234F',
    aadharCardNo: '123456789012',
    passportNo: 'M1234567',
    pfAccountNo: 'PF001234',
    bankAccountNo: 'ACC123456789',
    bankName: 'HDFC Bank',
    ifscCode: 'HDFC0001234'
  },
  {
    empCode: 'EMP002',
    name: 'Priya Sharma',
    branch: 'Delhi',
    doj: new Date('2023-03-10'),
    reportingManager: 'Rajesh Kumar',
    company: 'TechCorp Solutions',
    status: 'Active',
    gender: 'Female',
    dob: new Date('1992-07-22'),
    maritalStatus: 'Single',
    department: 'Marketing',
    designation: 'Marketing Manager',
    qualification: 'MBA Marketing',
    experience: 4,
    employmentStatus: 'Permanent',
    salaryOffered: 65000,
    annual: 780000,
    contactNumber: '+91-9876543211',
    officialEmailId: 'priya.sharma@techcorp.com',
    personalEmailId: 'priya.sharma92@gmail.com',
    currentAddress: '789 Corporate Plaza, Connaught Place, Delhi - 110001',
    permanentAddress: '321 Royal Gardens, Jaipur - 302001',
    panCardNo: 'BCDEF2345G',
    aadharCardNo: '234567890123',
    passportNo: 'P2345678',
    pfAccountNo: 'PF002345',
    bankAccountNo: 'ACC234567890',
    bankName: 'ICICI Bank',
    ifscCode: 'ICIC0002345'
  },
  {
    empCode: 'EMP003',
    name: 'Amit Patel',
    branch: 'Bangalore',
    doj: new Date('2022-11-20'),
    reportingManager: 'Neha Gupta',
    company: 'TechCorp Solutions',
    status: 'Active',
    gender: 'Male',
    dob: new Date('1988-12-05'),
    maritalStatus: 'Married',
    department: 'Human Resources',
    designation: 'HR Business Partner',
    qualification: 'MBA HR',
    experience: 7,
    employmentStatus: 'Permanent',
    salaryOffered: 70000,
    annual: 840000,
    contactNumber: '+91-9876543212',
    officialEmailId: 'amit.patel@techcorp.com',
    personalEmailId: 'amit.patel88@yahoo.com',
    currentAddress: '456 IT Park, Whitefield, Bangalore - 560066',
    permanentAddress: '789 Garden City, Ahmedabad - 380001',
    panCardNo: 'CDEFG3456H',
    aadharCardNo: '345678901234',
    passportNo: 'A3456789',
    pfAccountNo: 'PF003456',
    bankAccountNo: 'ACC345678901',
    bankName: 'SBI',
    ifscCode: 'SBIN0003456'
  },
  {
    empCode: 'EMP004',
    name: 'Sneha Reddy',
    branch: 'Hyderabad',
    doj: new Date('2023-05-08'),
    reportingManager: 'Karthik Rao',
    company: 'TechCorp Solutions',
    status: 'Active',
    gender: 'Female',
    dob: new Date('1995-04-18'),
    maritalStatus: 'Single',
    department: 'Finance',
    designation: 'Financial Analyst',
    qualification: 'CA, B.Com',
    experience: 3,
    employmentStatus: 'Permanent',
    salaryOffered: 55000,
    annual: 660000,
    contactNumber: '+91-9876543213',
    officialEmailId: 'sneha.reddy@techcorp.com',
    personalEmailId: 'sneha.reddy95@hotmail.com',
    currentAddress: '123 Financial District, Gachibowli, Hyderabad - 500032',
    permanentAddress: '456 Sunrise Colony, Vijayawada - 520001',
    panCardNo: 'DEFGH4567I',
    aadharCardNo: '456789012345',
    passportNo: 'S4567890',
    pfAccountNo: 'PF004567',
    bankAccountNo: 'ACC456789012',
    bankName: 'Axis Bank',
    ifscCode: 'UTIB0004567'
  },
  {
    empCode: 'EMP005',
    name: 'Rohit Mehta',
    branch: 'Chennai',
    doj: new Date('2022-09-12'),
    reportingManager: 'Deepika Nair',
    company: 'TechCorp Solutions',
    status: 'Active',
    gender: 'Male',
    dob: new Date('1991-08-30'),
    maritalStatus: 'Married',
    department: 'Sales',
    designation: 'Sales Manager',
    qualification: 'B.Tech, MBA Sales',
    experience: 6,
    employmentStatus: 'Permanent',
    salaryOffered: 80000,
    annual: 960000,
    contactNumber: '+91-9876543214',
    officialEmailId: 'rohit.mehta@techcorp.com',
    personalEmailId: 'rohit.mehta91@gmail.com',
    currentAddress: '789 Business Bay, OMR, Chennai - 600096',
    permanentAddress: '321 Lake View, Coimbatore - 641001',
    panCardNo: 'EFGHI5678J',
    aadharCardNo: '567890123456',
    passportNo: 'R5678901',
    pfAccountNo: 'PF005678',
    bankAccountNo: 'ACC567890123',
    bankName: 'Kotak Mahindra Bank',
    ifscCode: 'KKBK0005678'
  },
  {
    empCode: 'EMP006',
    name: 'Kavya Singh',
    branch: 'Pune',
    doj: new Date('2023-02-28'),
    reportingManager: 'Arjun Joshi',
    company: 'TechCorp Solutions',
    status: 'Active',
    gender: 'Female',
    dob: new Date('1993-11-12'),
    maritalStatus: 'Single',
    department: 'Quality Assurance',
    designation: 'QA Lead',
    qualification: 'B.E Computer Science',
    experience: 4,
    employmentStatus: 'Permanent',
    salaryOffered: 60000,
    annual: 720000,
    contactNumber: '+91-9876543215',
    officialEmailId: 'kavya.singh@techcorp.com',
    personalEmailId: 'kavya.singh93@outlook.com',
    currentAddress: '456 Tech Zone, Hinjewadi, Pune - 411057',
    permanentAddress: '789 Heritage Park, Lucknow - 226001',
    panCardNo: 'FGHIJ6789K',
    aadharCardNo: '678901234567',
    passportNo: 'K6789012',
    pfAccountNo: 'PF006789',
    bankAccountNo: 'ACC678901234',
    bankName: 'Yes Bank',
    ifscCode: 'YESB0006789'
  },
  {
    empCode: 'EMP007',
    name: 'Vikash Kumar',
    branch: 'Kolkata',
    doj: new Date('2023-06-15'),
    reportingManager: 'Anita Das',
    company: 'TechCorp Solutions',
    status: 'Active',
    gender: 'Male',
    dob: new Date('1989-01-25'),
    maritalStatus: 'Married',
    department: 'Operations',
    designation: 'Operations Manager',
    qualification: 'B.Tech Mechanical, MBA Operations',
    experience: 8,
    employmentStatus: 'Permanent',
    salaryOffered: 75000,
    annual: 900000,
    contactNumber: '+91-9876543216',
    officialEmailId: 'vikash.kumar@techcorp.com',
    personalEmailId: 'vikash.kumar89@rediffmail.com',
    currentAddress: '123 Business Complex, Salt Lake, Kolkata - 700091',
    permanentAddress: '456 River Side, Patna - 800001',
    panCardNo: 'GHIJK7890L',
    aadharCardNo: '789012345678',
    passportNo: 'V7890123',
    pfAccountNo: 'PF007890',
    bankAccountNo: 'ACC789012345',
    bankName: 'PNB',
    ifscCode: 'PUNB0007890'
  },
  {
    empCode: 'EMP008',
    name: 'Meera Jain',
    branch: 'Ahmedabad',
    doj: new Date('2023-04-03'),
    reportingManager: 'Suresh Patel',
    company: 'TechCorp Solutions',
    status: 'Active',
    gender: 'Female',
    dob: new Date('1994-09-14'),
    maritalStatus: 'Married',
    department: 'Customer Support',
    designation: 'Customer Success Manager',
    qualification: 'B.Com, Diploma in Customer Relations',
    experience: 3,
    employmentStatus: 'Permanent',
    salaryOffered: 50000,
    annual: 600000,
    contactNumber: '+91-9876543217',
    officialEmailId: 'meera.jain@techcorp.com',
    personalEmailId: 'meera.jain94@gmail.com',
    currentAddress: '789 Corporate Center, Satellite, Ahmedabad - 380015',
    permanentAddress: '321 Golden Heights, Indore - 452001',
    panCardNo: 'HIJKL8901M',
    aadharCardNo: '890123456789',
    passportNo: 'M8901234',
    pfAccountNo: 'PF008901',
    bankAccountNo: 'ACC890123456',
    bankName: 'Bank of Baroda',
    ifscCode: 'BARB0008901'
  },
  {
    empCode: 'EMP009',
    name: 'Ravi Tiwari',
    branch: 'Lucknow',
    doj: new Date('2022-12-05'),
    reportingManager: 'Pooja Agarwal',
    company: 'TechCorp Solutions',
    status: 'Active',
    gender: 'Male',
    dob: new Date('1987-06-08'),
    maritalStatus: 'Married',
    department: 'Business Development',
    designation: 'Business Development Manager',
    qualification: 'MBA Business Development',
    experience: 9,
    employmentStatus: 'Permanent',
    salaryOffered: 85000,
    annual: 1020000,
    contactNumber: '+91-9876543218',
    officialEmailId: 'ravi.tiwari@techcorp.com',
    personalEmailId: 'ravi.tiwari87@yahoo.in',
    currentAddress: '456 Business Hub, Gomti Nagar, Lucknow - 226010',
    permanentAddress: '789 Garden Colony, Kanpur - 208001',
    panCardNo: 'IJKLM9012N',
    aadharCardNo: '901234567890',
    passportNo: 'T9012345',
    pfAccountNo: 'PF009012',
    bankAccountNo: 'ACC901234567',
    bankName: 'Canara Bank',
    ifscCode: 'CNRB0009012'
  },
  {
    empCode: 'EMP010',
    name: 'Anjali Verma',
    branch: 'Jaipur',
    doj: new Date('2023-07-20'),
    reportingManager: 'Manish Sharma',
    company: 'TechCorp Solutions',
    status: 'Active',
    gender: 'Female',
    dob: new Date('1996-02-28'),
    maritalStatus: 'Single',
    department: 'Design',
    designation: 'UI/UX Designer',
    qualification: 'B.Des, Certification in UX Design',
    experience: 2,
    employmentStatus: 'Permanent',
    salaryOffered: 45000,
    annual: 540000,
    contactNumber: '+91-9876543219',
    officialEmailId: 'anjali.verma@techcorp.com',
    personalEmailId: 'anjali.verma96@gmail.com',
    currentAddress: '123 Design Studio, Malviya Nagar, Jaipur - 302017',
    permanentAddress: '456 Pink City Residency, Jaipur - 302001',
    panCardNo: 'JKLMN0123O',
    aadharCardNo: '012345678901',
    passportNo: 'A0123456',
    pfAccountNo: 'PF010123',
    bankAccountNo: 'ACC012345678',
    bankName: 'IndusInd Bank',
    ifscCode: 'INDB0010123'
  },
  {
    empCode: 'EMP011',
    name: 'Sanjay Agarwal',
    branch: 'Nagpur',
    doj: new Date('2023-01-30'),
    reportingManager: 'Rekha Patil',
    company: 'TechCorp Solutions',
    status: 'Active',
    gender: 'Male',
    dob: new Date('1985-10-17'),
    maritalStatus: 'Married',
    department: 'Legal',
    designation: 'Legal Counsel',
    qualification: 'LLB, LLM Corporate Law',
    experience: 12,
    employmentStatus: 'Permanent',
    salaryOffered: 90000,
    annual: 1080000,
    contactNumber: '+91-9876543220',
    officialEmailId: 'sanjay.agarwal@techcorp.com',
    personalEmailId: 'sanjay.agarwal85@hotmail.com',
    currentAddress: '789 Legal Complex, Civil Lines, Nagpur - 440001',
    permanentAddress: '321 Lawyer Colony, Bhopal - 462001',
    panCardNo: 'KLMNO1234P',
    aadharCardNo: '123456789012',
    passportNo: 'S1234567',
    pfAccountNo: 'PF011234',
    bankAccountNo: 'ACC123456789',
    bankName: 'Union Bank',
    ifscCode: 'UBIN0011234'
  },
  {
    empCode: 'EMP012',
    name: 'Divya Nair',
    branch: 'Kochi',
    doj: new Date('2023-08-14'),
    reportingManager: 'Krishna Pillai',
    company: 'TechCorp Solutions',
    status: 'Active',
    gender: 'Female',
    dob: new Date('1992-05-03'),
    maritalStatus: 'Married',
    department: 'Research & Development',
    designation: 'Research Analyst',
    qualification: 'M.Tech Computer Science, PhD (Pursuing)',
    experience: 5,
    employmentStatus: 'Permanent',
    salaryOffered: 70000,
    annual: 840000,
    contactNumber: '+91-9876543221',
    officialEmailId: 'divya.nair@techcorp.com',
    personalEmailId: 'divya.nair92@gmail.com',
    currentAddress: '456 Tech Park, Infopark, Kochi - 682030',
    permanentAddress: '789 Backwater View, Alappuzha - 688001',
    panCardNo: 'LMNOP2345Q',
    aadharCardNo: '234567890123',
    passportNo: 'D2345678',
    pfAccountNo: 'PF012345',
    bankAccountNo: 'ACC234567890',
    bankName: 'Federal Bank',
    ifscCode: 'FDRL0012345'
  },
  {
    empCode: 'EMP013',
    name: 'Arpit Gupta',
    branch: 'Indore',
    doj: new Date('2022-10-10'),
    reportingManager: 'Sunita Joshi',
    company: 'TechCorp Solutions',
    status: 'Active',
    gender: 'Male',
    dob: new Date('1990-12-20'),
    maritalStatus: 'Single',
    department: 'Information Technology',
    designation: 'System Administrator',
    qualification: 'B.Tech IT, Certification in Cloud Computing',
    experience: 6,
    employmentStatus: 'Permanent',
    salaryOffered: 65000,
    annual: 780000,
    contactNumber: '+91-9876543222',
    officialEmailId: 'arpit.gupta@techcorp.com',
    personalEmailId: 'arpit.gupta90@outlook.com',
    currentAddress: '123 IT Center, Vijay Nagar, Indore - 452010',
    permanentAddress: '456 Tech Valley, Gwalior - 474001',
    panCardNo: 'MNOPQ3456R',
    aadharCardNo: '345678901234',
    passportNo: 'G3456789',
    pfAccountNo: 'PF013456',
    bankAccountNo: 'ACC345678901',
    bankName: 'IDFC First Bank',
    ifscCode: 'IDFB0013456'
  },
  {
    empCode: 'EMP014',
    name: 'Tanya Kapoor',
    branch: 'Chandigarh',
    doj: new Date('2023-09-05'),
    reportingManager: 'Rajiv Singh',
    company: 'TechCorp Solutions',
    status: 'Active',
    gender: 'Female',
    dob: new Date('1993-03-08'),
    maritalStatus: 'Single',
    department: 'Content Marketing',
    designation: 'Content Strategist',
    qualification: 'Masters in Mass Communication',
    experience: 4,
    employmentStatus: 'Permanent',
    salaryOffered: 55000,
    annual: 660000,
    contactNumber: '+91-9876543223',
    officialEmailId: 'tanya.kapoor@techcorp.com',
    personalEmailId: 'tanya.kapoor93@gmail.com',
    currentAddress: '789 Media Hub, Sector 34, Chandigarh - 160022',
    permanentAddress: '321 Rose Garden, Patiala - 147001',
    panCardNo: 'NOPQR4567S',
    aadharCardNo: '456789012345',
    passportNo: 'T4567890',
    pfAccountNo: 'PF014567',
    bankAccountNo: 'ACC456789012',
    bankName: 'Standard Chartered',
    ifscCode: 'SCBL0014567'
  },
  {
    empCode: 'EMP015',
    name: 'Karan Shah',
    branch: 'Surat',
    doj: new Date('2023-03-22'),
    reportingManager: 'Nisha Desai',
    company: 'TechCorp Solutions',
    status: 'Active',
    gender: 'Male',
    dob: new Date('1991-11-15'),
    maritalStatus: 'Married',
    department: 'Supply Chain',
    designation: 'Supply Chain Analyst',
    qualification: 'B.Tech Industrial Engineering, MBA Supply Chain',
    experience: 5,
    employmentStatus: 'Permanent',
    salaryOffered: 60000,
    annual: 720000,
    contactNumber: '+91-9876543224',
    officialEmailId: 'karan.shah@techcorp.com',
    personalEmailId: 'karan.shah91@yahoo.com',
    currentAddress: '456 Diamond Plaza, Ring Road, Surat - 395002',
    permanentAddress: '789 Textile City, Rajkot - 360001',
    panCardNo: 'OPQRS5678T',
    aadharCardNo: '567890123456',
    passportNo: 'K5678901',
    pfAccountNo: 'PF015678',
    bankAccountNo: 'ACC567890123',
    bankName: 'HDFC Bank',
    ifscCode: 'HDFC0015678'
  }
];

async function addDummyEmployees() {
  try {
    console.log('🔗 Connecting to MongoDB...');
    await mongoose.connect(mongoUri, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log('✅ Connected to MongoDB successfully!');

    console.log('🧹 Clearing existing employees...');
    await Employee.deleteMany({});
    console.log('✅ Existing employees cleared!');

    console.log('📝 Adding 15 dummy employees...');
    const result = await Employee.insertMany(dummyEmployees);
    console.log(`✅ Successfully added ${result.length} employees!`);

    // Display summary
    console.log('\n📊 Employee Summary:');
    const departments = await Employee.aggregate([
      { $group: { _id: '$department', count: { $sum: 1 } } },
      { $sort: { count: -1 } }
    ]);
    
    console.log('\nEmployees by Department:');
    departments.forEach(dept => {
      console.log(`  ${dept._id}: ${dept.count} employees`);
    });

    const branches = await Employee.aggregate([
      { $group: { _id: '$branch', count: { $sum: 1 } } },
      { $sort: { count: -1 } }
    ]);
    
    console.log('\nEmployees by Branch:');
    branches.forEach(branch => {
      console.log(`  ${branch._id}: ${branch.count} employees`);
    });

    console.log('\n🎉 Dummy employee data added successfully!');

  } catch (error) {
    console.error('❌ Error adding dummy employees:', error);
  } finally {
    await mongoose.disconnect();
    console.log('🔌 Disconnected from MongoDB');
  }
}

// Run the script
addDummyEmployees();
