const mongoose = require('mongoose');
const FieldExecutive = require('../models/FieldExecutive');

// MongoDB connection
const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/crmdb';

// Sample field executive data matching screenshot metrics
const sampleFieldExecutives = [
  {
    employeeId: 'FE001',
    name: 'Rajesh Kumar',
    region: 'North',
    team: 'Alpha',
    allocated: 45,
    visited: 38,
    validVisits: 35,
    distance: 12.5,
    photos: 32,
    avgVisitsPerDay: 7.6,
    avgTimePerVisit: 25,
    efficiencyScore: 92,
    collectionAmount: 125000,
    targetAchievement: 105,
    settlements: 8,
    attendance: 96,
    overallRating: 'Excellent',
    phone: '+91-9876543210',
    email: 'rajesh.kumar@company.com',
    joinDate: new Date('2023-01-15'),
    isActive: true,
    lastActiveDate: new Date(),
  },
  {
    employeeId: 'FE002',
    name: 'Priya Sharma',
    region: 'South',
    team: 'Beta',
    allocated: 42,
    visited: 36,
    validVisits: 31,
    distance: 10.8,
    photos: 28,
    avgVisitsPerDay: 7.2,
    avgTimePerVisit: 28,
    efficiencyScore: 86,
    collectionAmount: 98000,
    targetAchievement: 92,
    settlements: 6,
    attendance: 94,
    overallRating: 'Good',
    phone: '+91-9876543211',
    email: 'priya.sharma@company.com',
    joinDate: new Date('2023-02-20'),
    isActive: true,
    lastActiveDate: new Date(),
  },
  {
    employeeId: 'FE003',
    name: 'Amit Patel',
    region: 'East',
    team: 'Gamma',
    allocated: 50,
    visited: 42,
    validVisits: 38,
    distance: 15.2,
    photos: 35,
    avgVisitsPerDay: 8.4,
    avgTimePerVisit: 22,
    efficiencyScore: 90,
    collectionAmount: 142000,
    targetAchievement: 108,
    settlements: 9,
    attendance: 98,
    overallRating: 'Excellent',
    phone: '+91-9876543212',
    email: 'amit.patel@company.com',
    joinDate: new Date('2023-01-10'),
    isActive: true,
    lastActiveDate: new Date(),
  },
  {
    employeeId: 'FE004',
    name: 'Sneha Reddy',
    region: 'West',
    team: 'Delta',
    allocated: 38,
    visited: 32,
    validVisits: 28,
    distance: 9.5,
    photos: 25,
    avgVisitsPerDay: 6.4,
    avgTimePerVisit: 30,
    efficiencyScore: 82,
    collectionAmount: 87000,
    targetAchievement: 85,
    settlements: 5,
    attendance: 90,
    overallRating: 'Good',
    phone: '+91-9876543213',
    email: 'sneha.reddy@company.com',
    joinDate: new Date('2023-03-05'),
    isActive: true,
    lastActiveDate: new Date(),
  },
  {
    employeeId: 'FE005',
    name: 'Vikram Singh',
    region: 'North',
    team: 'Alpha',
    allocated: 48,
    visited: 40,
    validVisits: 36,
    distance: 13.8,
    photos: 33,
    avgVisitsPerDay: 8.0,
    avgTimePerVisit: 24,
    efficiencyScore: 90,
    collectionAmount: 118000,
    targetAchievement: 98,
    settlements: 7,
    attendance: 95,
    overallRating: 'Excellent',
    phone: '+91-9876543214',
    email: 'vikram.singh@company.com',
    joinDate: new Date('2023-02-01'),
    isActive: true,
    lastActiveDate: new Date(),
  },
  {
    employeeId: 'FE006',
    name: 'Anjali Verma',
    region: 'South',
    team: 'Beta',
    allocated: 40,
    visited: 34,
    validVisits: 29,
    distance: 11.2,
    photos: 27,
    avgVisitsPerDay: 6.8,
    avgTimePerVisit: 27,
    efficiencyScore: 85,
    collectionAmount: 92000,
    targetAchievement: 88,
    settlements: 6,
    attendance: 92,
    overallRating: 'Good',
    phone: '+91-9876543215',
    email: 'anjali.verma@company.com',
    joinDate: new Date('2023-03-15'),
    isActive: true,
    lastActiveDate: new Date(),
  },
  {
    employeeId: 'FE007',
    name: 'Rahul Desai',
    region: 'East',
    team: 'Gamma',
    allocated: 52,
    visited: 44,
    validVisits: 40,
    distance: 16.5,
    photos: 38,
    avgVisitsPerDay: 8.8,
    avgTimePerVisit: 21,
    efficiencyScore: 91,
    collectionAmount: 156000,
    targetAchievement: 112,
    settlements: 10,
    attendance: 97,
    overallRating: 'Excellent',
    phone: '+91-9876543216',
    email: 'rahul.desai@company.com',
    joinDate: new Date('2023-01-20'),
    isActive: true,
    lastActiveDate: new Date(),
  },
  {
    employeeId: 'FE008',
    name: 'Kavita Nair',
    region: 'West',
    team: 'Delta',
    allocated: 36,
    visited: 30,
    validVisits: 25,
    distance: 8.9,
    photos: 22,
    avgVisitsPerDay: 6.0,
    avgTimePerVisit: 32,
    efficiencyScore: 78,
    collectionAmount: 75000,
    targetAchievement: 80,
    settlements: 4,
    attendance: 88,
    overallRating: 'Average',
    phone: '+91-9876543217',
    email: 'kavita.nair@company.com',
    joinDate: new Date('2023-04-10'),
    isActive: true,
    lastActiveDate: new Date(),
  },
  {
    employeeId: 'FE009',
    name: 'Suresh Rao',
    region: 'North',
    team: 'Alpha',
    allocated: 46,
    visited: 39,
    validVisits: 34,
    distance: 12.1,
    photos: 31,
    avgVisitsPerDay: 7.8,
    avgTimePerVisit: 26,
    efficiencyScore: 87,
    collectionAmount: 108000,
    targetAchievement: 95,
    settlements: 7,
    attendance: 93,
    overallRating: 'Good',
    phone: '+91-9876543218',
    email: 'suresh.rao@company.com',
    joinDate: new Date('2023-02-15'),
    isActive: true,
    lastActiveDate: new Date(),
  },
  {
    employeeId: 'FE010',
    name: 'Meena Joshi',
    region: 'South',
    team: 'Beta',
    allocated: 44,
    visited: 37,
    validVisits: 32,
    distance: 11.5,
    photos: 29,
    avgVisitsPerDay: 7.4,
    avgTimePerVisit: 27,
    efficiencyScore: 86,
    collectionAmount: 102000,
    targetAchievement: 91,
    settlements: 6,
    attendance: 94,
    overallRating: 'Good',
    phone: '+91-9876543219',
    email: 'meena.joshi@company.com',
    joinDate: new Date('2023-03-01'),
    isActive: true,
    lastActiveDate: new Date(),
  },
  {
    employeeId: 'FE011',
    name: 'Arjun Mehta',
    region: 'East',
    team: 'Gamma',
    allocated: 49,
    visited: 41,
    validVisits: 37,
    distance: 14.8,
    photos: 34,
    avgVisitsPerDay: 8.2,
    avgTimePerVisit: 23,
    efficiencyScore: 90,
    collectionAmount: 135000,
    targetAchievement: 102,
    settlements: 8,
    attendance: 96,
    overallRating: 'Excellent',
    phone: '+91-9876543220',
    email: 'arjun.mehta@company.com',
    joinDate: new Date('2023-01-25'),
    isActive: true,
    lastActiveDate: new Date(),
  },
  {
    employeeId: 'FE012',
    name: 'Pooja Iyer',
    region: 'West',
    team: 'Delta',
    allocated: 41,
    visited: 35,
    validVisits: 30,
    distance: 10.5,
    photos: 27,
    avgVisitsPerDay: 7.0,
    avgTimePerVisit: 28,
    efficiencyScore: 85,
    collectionAmount: 95000,
    targetAchievement: 89,
    settlements: 6,
    attendance: 91,
    overallRating: 'Good',
    phone: '+91-9876543221',
    email: 'pooja.iyer@company.com',
    joinDate: new Date('2023-03-20'),
    isActive: true,
    lastActiveDate: new Date(),
  },
  {
    employeeId: 'FE013',
    name: 'Karan Kapoor',
    region: 'North',
    team: 'Alpha',
    allocated: 47,
    visited: 40,
    validVisits: 35,
    distance: 13.2,
    photos: 32,
    avgVisitsPerDay: 8.0,
    avgTimePerVisit: 25,
    efficiencyScore: 88,
    collectionAmount: 115000,
    targetAchievement: 97,
    settlements: 7,
    attendance: 95,
    overallRating: 'Good',
    phone: '+91-9876543222',
    email: 'karan.kapoor@company.com',
    joinDate: new Date('2023-02-10'),
    isActive: true,
    lastActiveDate: new Date(),
  },
  {
    employeeId: 'FE014',
    name: 'Divya Pillai',
    region: 'South',
    team: 'Beta',
    allocated: 43,
    visited: 36,
    validVisits: 31,
    distance: 11.0,
    photos: 28,
    avgVisitsPerDay: 7.2,
    avgTimePerVisit: 27,
    efficiencyScore: 86,
    collectionAmount: 99000,
    targetAchievement: 90,
    settlements: 6,
    attendance: 93,
    overallRating: 'Good',
    phone: '+91-9876543223',
    email: 'divya.pillai@company.com',
    joinDate: new Date('2023-03-10'),
    isActive: true,
    lastActiveDate: new Date(),
  },
  {
    employeeId: 'FE015',
    name: 'Sanjay Gupta',
    region: 'East',
    team: 'Gamma',
    allocated: 51,
    visited: 43,
    validVisits: 39,
    distance: 15.8,
    photos: 36,
    avgVisitsPerDay: 8.6,
    avgTimePerVisit: 22,
    efficiencyScore: 91,
    collectionAmount: 148000,
    targetAchievement: 110,
    settlements: 9,
    attendance: 98,
    overallRating: 'Excellent',
    phone: '+91-9876543224',
    email: 'sanjay.gupta@company.com',
    joinDate: new Date('2023-01-15'),
    isActive: true,
    lastActiveDate: new Date(),
  },
];

const seedFieldExecutives = async () => {
  try {
    // Connect to MongoDB
    await mongoose.connect(MONGODB_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log('✅ Connected to MongoDB');

    // Clear existing field executives
    await FieldExecutive.deleteMany({});
    console.log('🗑️  Cleared existing field executives');

    // Insert sample data
    const insertedFEs = await FieldExecutive.insertMany(sampleFieldExecutives);
    console.log(`✅ Successfully seeded ${insertedFEs.length} field executives`);

    // Display summary
    console.log('\n📊 Field Executive Summary:');
    const summary = await FieldExecutive.aggregate([
      {
        $group: {
          _id: null,
          totalFEs: { $sum: 1 },
          totalAllocated: { $sum: '$allocated' },
          totalVisited: { $sum: '$visited' },
          totalValidVisits: { $sum: '$validVisits' },
          totalDistance: { $sum: '$distance' },
          totalPhotos: { $sum: '$photos' },
          totalCollection: { $sum: '$collectionAmount' },
          avgEfficiency: { $avg: '$efficiencyScore' },
          avgAttendance: { $avg: '$attendance' },
        },
      },
    ]);

    if (summary.length > 0) {
      const stats = summary[0];
      console.log(`Total FEs: ${stats.totalFEs}`);
      console.log(`Total Allocated: ${stats.totalAllocated}`);
      console.log(`Total Visited: ${stats.totalVisited}`);
      console.log(`Total Valid Visits: ${stats.totalValidVisits}`);
      console.log(`Total Distance: ${stats.totalDistance.toFixed(2)} KM`);
      console.log(`Total Photos: ${stats.totalPhotos}`);
      console.log(`Total Collection: ₹${stats.totalCollection.toLocaleString()}`);
      console.log(`Avg Efficiency: ${stats.avgEfficiency.toFixed(2)}%`);
      console.log(`Avg Attendance: ${stats.avgAttendance.toFixed(2)}%`);
    }

    // Display regional distribution
    console.log('\n🌍 Regional Distribution:');
    const regionStats = await FieldExecutive.aggregate([
      {
        $group: {
          _id: '$region',
          count: { $sum: 1 },
          totalCollection: { $sum: '$collectionAmount' },
          avgEfficiency: { $avg: '$efficiencyScore' },
        },
      },
      { $sort: { count: -1 } },
    ]);

    regionStats.forEach((region) => {
      console.log(
        `${region._id}: ${region.count} FEs | Collection: ₹${region.totalCollection.toLocaleString()} | Avg Efficiency: ${region.avgEfficiency.toFixed(2)}%`
      );
    });

    console.log('\n✨ Seeding completed successfully!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding field executives:', error);
    process.exit(1);
  }
};

// Run the seed script
seedFieldExecutives();
